### ISSUE TITLE
What does ZFW do?

### ISSUE THREAD

**Issue by qrkourier** [r-caamano/zfw#106]
Is this accurate?

> ZFW automatically configures your Linux firewall according to Ziti events. This can be used to ensure that Linux is configured to accept incoming connections for the hosted Ziti services assigned to the device and to masquerade as the source address of the Ziti client using the Ziti service hosted by the device (source transparency).

**Comment by r-caamano** [comment]
ZFW is a tc based FW which uses tc-ebpf as a stateful firewall/filter automatically open ports to ziti services based on ZITI events and also allows for user based entries for passthough or local device terminated connections.  It does not auto configure masquerade though it can work in conjunction with it if configured.  If outbound tracking is enabled which is default for ExternalInterfaces and optional for InternalInterfaces as provisioned in /opt/openziti/etc/ebpf_config.json then it will allow return traffic for traffic initiated from local LAN or containers running on device toward internet/Wan.   Automatic ziti port opening is only on by default for interfaces configured as InternalInterfaces.  Transparency that is mentioned in the READM refers to ziti source transparency in which ZET can bind to a loopback local route corresponding to the allowedSourcesAddresses key in the host.v1 configuration on the hosting ZET.  ZET currently does not auto create these loopback bind routes (unlike ziti-router) so ZFW created them on behalf of ZET after reading the allowedSourceAddresses in the ZET dump log hosted services, since allowedSourcesAddresses are currently not sent as ziti events on the ZET event sock.  ZFW also overcomes ZET limitation with regards to bi-directional transparency (both egress and ingress service from same transparent address simultaneously) by using a combination of tc-ebpf redirect and xdc redirects between the lan interface(s) and the ziti tun interface.  xdp runs on the tun interface and tc-ebpf on the lan interface.  When a packet matching a ziti ingress service is received on the lan (tc) interface, if index source / dest IPs and source/dest MAC are stored in an ebpf hash map and represent a tunnel forwarding state.  The tc interface also directly forwards the packet to the ziti tun interface (negating the need for routing lookup).  Upon reception of a packet from ZET, the tun (xdc) interface checks to see  if a tun state exists and extracts the information needed to build an ethernet header/ip header to forward the traffic directly back to the originating lan interface.  This effectively bi-passes the kernel's stack, which is a necessary step since the Kernel would normally consider the traffic with a source address that is also bound to it (i.e. the loopback route bound to for transparency binding) as spoofed traffic and drops it before it can be routed back to its intended client destination.  On certain platforms i.e. arm64 an additional step must be taken if source transparency is required, which is to also remove the link level route that ZET installs on the TUN interface for interception.  Bi-directional transparency is not on by default for arm64 but can be enabled with environmental variable as described in the README.  This is because removing the link route breaks internal ZET tunnel (internal host running ZET) initiated sessions toward ziti.  However, bi-directional transparency is usually only deployed for scenarios where ZET is acting as router and not an end host so this compromise makes sense for those scenarios.  X86 platform does not require removal of the route so both internal interception and bi-directional transparency are supported simultaneously by default.  Let me know if that helps.

**Comment by qrkourier** [comment]
Thank you. Moving discussion to new repo home: https://github.com/netfoundry/zfw
